name: @name@
version: @version@
main: click.seichi.@lname@.@name@
api-version: 1.15
load: STARTUP


commands:
  ready:
    description: Ready to the game
    usage: /ready
    aliases: [r]
    permission: petra.ready
    permission-message: You don't have <permission>

permissions:
  petra.ready:
    description: Ready to the game
    default: true