name: @name@
version: @version@
main: click.seichi.@lname@.@name@
api-version: 1.15
load: STARTUP


commands:
  ready:
    usage: /ready
    aliases: [r]
    permission: petra.ready
    permission-message: You don't have <permission>
  start:
    usage: /start
    permission: petra.start
    permission-message: You don't have <permission>

permissions:
  petra.ready:
    description: Ready to the game
    default: true
  petra.start:
    description: Start the game force
    default: op