name: @name@
version: @version@
main: click.seichi.@lname@.@name@
api-version: 1.15
load: STARTUP


commands:
  ready:
    description: This is ready command.
    usage: /ready
    aliases: [r]
    default: default
    permission: petra.vote
    permission-message: You don't have <permission>