name: CD
on:
  workflow_dispatch:
  push:
    branches:
      - main
concurrency:
  group: deploy
  cancel-in-progress: true
jobs:
  build:
    name: Build jar
    uses: ./.github/workflows/ci.yml
  deploy:
    name: Deploy jar
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: jar
      - name: Exports SSH private key
        run: |
          echo "${{ secrets.DEPLOY_SECRET_KEY }}" > id_rsa
          chmod 600 id_rsa
      - name: Scp artifact
        run: scp -o 'StrictHostKeyChecking no' -P ${{ secrets.PORT }} -i id_rsa *.jar ${{ secrets.USERNAME }}@${{ secrets.HOST }}:${{ secrets.DEPLOY_TARGET_DIRECTORY }}
