name: CI
on:
  workflow_call:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - main
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: 'gradle'
    - name: Build with Gradle
      # CVE-2023-30853 - https://github.com/advisories/GHSA-h3qr-39j9-4r5v
      uses: gradle/gradle-build-action@v2.4.2
      with:
        arguments: jar
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: jar
        path: build/libs/*.jar
