name: CI
on:
  workflow_call:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: 'gradle'
    - name: Build with Gradle
      run: ./gradlew jar
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: jar
        path: build/libs/*.jar
